version: "3.8"

services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    networks:
      - app_network 

  db:
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER} 
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD} 
      POSTGRES_DB: ${POSTGRES_DB} 
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    ports:
      - "5433:5432"
    networks:
      - app_network 

  web:
    build:
      context: .
    command: >
      sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py collectstatic && python manage.py import_finorgs && gunicorn --bind 0.0.0.0:8000 core.wsgi:application"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - app_network 

  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web
    networks:
      - app_network 

volumes:
  postgres_data:

networks:
  app_network: 
    driver: bridge
