# Generated by Django 5.1.5 on 2025-01-20 11:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialOrganization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('first_director', models.CharField(max_length=255)),
                ('board_of_directors', models.TextField()),
                ('chairman_of_the_board', models.CharField(max_length=255)),
                ('board_members', models.TextField()),
                ('other_executives', models.TextField()),
                ('director', models.CharField(max_length=255)),
                ('chief_accountant', models.CharField(max_length=255)),
                ('bin', models.CharField(max_length=20, unique=True)),
                ('address', models.TextField()),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField()),
                ('license', models.CharField(max_length=255)),
                ('branches', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FinancialOrganizationNews',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('published_date', models.DateTimeField()),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financial_orgs.financialorganization')),
            ],
        ),
    ]
