# Generated by Django 5.1.5 on 2025-01-20 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_orgs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialorganization',
            name='chairman_of_the_board',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='financialorganization',
            name='chief_accountant',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='financialorganization',
            name='director',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='financialorganization',
            name='first_director',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='financialorganization',
            name='license',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='financialorganization',
            name='name',
            field=models.TextField(),
        ),
    ]
