# Generated by Django 5.1.5 on 2025-01-20 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_orgs', '0002_alter_financialorganization_chairman_of_the_board_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialorganization',
            name='bin',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='financialorganization',
            name='phone_number',
            field=models.TextField(),
        ),
    ]
